services:
  ollama:
    # https://hub.docker.com/r/ollama/ollama
    # https://github.com/ollama/ollama
    # image: ollama/ollama:latest
    # AMD - BEGIN
    # AMD Radeon RX 6600 (gfx1030) ROCm configuration
    image: ollama/ollama:rocm
    devices:
      - /dev/kfd
      - /dev/dri
    environment:
      - OLLAMA_DEBUG=1
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
    # AMD - END
    pull_policy: always
    container_name: ollama
    # Uncomment below to expose Ollama API outside the container stack
    #ports:
    #  - 11434:11434
    volumes:
      - ./data/ollama:/root/.ollama
    tty: true
    # NVIDIA - BEGIN - NEW (ONLY FOR NIXOS?)
    # Uncomment this part if you have a NVIDIA graphics card and
    # you want to use it with Ollama
    # For more information https://hub.docker.com/r/ollama/ollama and check
    # Nvidia GPU
    # For specific information about NixOS configuration check
    # https://nixos.org/manual/nixpkgs/unstable/#using-docker-compose
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: cdi
    #           device_ids:
    #             - nvidia.com/gpu=all
    #           capabilities: [gpu]
    # NVIDIA - END - NEW (ONLY FOR NIXOS?)

  open-webui:
    # https://github.com/open-webui/open-webui
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      - ollama
    ports:
      - "0.0.0.0:3000:8080"
    environment:
      OLLAMA_BASE_URL: "http://ollama:11434"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./data/open-webui:/app/backend/data

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: always
    ports:
      - "0.0.0.0:3001:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data/searxng/core-config/:/etc/searxng/:rw
      - ./data/searxng/data:/var/cache/searxng/

  valkey:
    container_name: valkey
    image: docker.io/valkey/valkey:9-alpine
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - ./data/valkey/data:/data/:rw

  open-terminal:
    image: ghcr.io/open-webui/open-terminal:latest
    container_name: open-terminal
    volumes:
      - /home/egarcia/temp:/home/user
    environment:
      - OPEN_TERMINAL_API_KEY=your-secret-key
